### ISSUE TITLE
[FEATURE REQUEST] Highscores

### ISSUE THREAD

**Issue by KendallDoesCoding** [d17012002/Birdy-Game#1]
I really love this game, but there's one thing missing for sure, I hate it when the level gets over, and you get a great score and then it's lost for eternity, it will be great if there's some kind of highscore system, that lists the top 5 highscores you got.

What do you think?

**Comment by d17012002** [comment]
I made this project long back and only used _frontend web technologies_ that is why some features are lacking. Definitely I'll take this suggestion into consideration but as my hands are full right now lately I'll be adding this feature. Although, this repository is open for contributions.

**Comment by KendallDoesCoding** [comment]
> I made this project long back and only used _frontend web technologies_ that is why some features are lacking. Definitely I'll take this suggestion into consideration but as my hands are full right now lately I'll be adding this feature. Although, this repository is open for contributions.

Ok cool! I don't know JS too well, so I don't think I can help you with this, sadly, but it was just a idea!
